"""baseline schema as shipped by v2.12

The schema every farm was already running when Boord adopted Alembic, so it
is written down here once and every later change is a migration on top of it.

An existing farm database is never actually run through this migration - it
already has these tables. backend/migrate.py brings it up to this exact
shape with the old additive catch-up (db.legacy_schema_catch_up) and then
*stamps* it at this revision. Only a brand-new install runs the CREATE TABLE
statements below, which is the point: a fresh install and an upgraded farm
end up at the same revision by different routes.

Because of that, this file must keep matching what SQLModel.metadata would
create. scripts/selftest.py builds a database both ways and diffs them.

Revision ID: 8bc3a7dc4b1e
Revises: 
Created: 2026-08-27 18:10:37.039710

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401 - autogenerate renders sqlmodel.sql.sqltypes.AutoString


revision = '8bc3a7dc4b1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adminuser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('block',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('variety', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trees', sa.Integer(), nullable=False),
    sa.Column('hectares', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ownerviewtoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ratesetting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('rate_type', sa.Enum('per_kg', 'per_crate_tier', name='ratetype'), nullable=False),
    sa.Column('default_rate_per_kg', sa.Float(), nullable=False),
    sa.Column('tier_rates_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setupstate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_own_farm', sa.Boolean(), nullable=False),
    sa.Column('packing_rate_per_kg', sa.Float(), nullable=False),
    sa.Column('packing_rate_per_crate', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('systemsetting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('farm_location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('green_to_yellow_minutes', sa.Integer(), nullable=False),
    sa.Column('yellow_to_red_minutes', sa.Integer(), nullable=False),
    sa.Column('current_harvest_year', sa.Integer(), nullable=False),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lon', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('induna', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weatherhistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('temp_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('dew_point_c', sa.Float(), nullable=True),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('weather_code', sa.Integer(), nullable=True),
    sa.Column('condition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('wind_speed_kmh', sa.Float(), nullable=True),
    sa.Column('soil_temp_6cm_c', sa.Float(), nullable=True),
    sa.Column('uv_index', sa.Float(), nullable=True),
    sa.Column('sunshine_duration_s', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weatherhistory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weatherhistory_timestamp'), ['timestamp'], unique=True)

    op.create_table('device',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('station', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('field', 'packhouse', 'admin', name='devicerole'), nullable=False),
    sa.Column('team_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('induna', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_capturer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historicalannualyield',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('kg', sa.Float(), nullable=False),
    sa.Column('estimated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['block.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historicalharvest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('harvest_date', sa.Date(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('kg', sa.Float(), nullable=False),
    sa.Column('estimated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['block.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bank', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('team_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('whatsapp_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('photo_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slip_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('team_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('driver', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_crates', sa.Integer(), nullable=False),
    sa.Column('total_kg', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('created', 'in_transit', 'received', 'processing_complete', name='lotstatus'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('weather_temp', sa.Float(), nullable=True),
    sa.Column('weather_humidity', sa.Float(), nullable=True),
    sa.Column('weather_condition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('split_from_slip_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slip_number')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_kg', sa.Float(), nullable=False),
    sa.Column('rate_applied', sa.Float(), nullable=False),
    sa.Column('amount_due', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('harvestrecord',
    sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('worker_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('block_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('deduction_kg', sa.Float(), nullable=False),
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('team_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('weather_temp', sa.Float(), nullable=True),
    sa.Column('weather_humidity', sa.Float(), nullable=True),
    sa.Column('weather_condition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('edited_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['block.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lot.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('prepackrecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('crates', sa.Integer(), nullable=False),
    sa.Column('dominant_block_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('operator', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['dominant_block_id'], ['block.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receivingrecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('expected_crates', sa.Integer(), nullable=False),
    sa.Column('actual_crates', sa.Integer(), nullable=False),
    sa.Column('discrepancy', sa.Integer(), nullable=False),
    sa.Column('condition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('waste_kg', sa.Float(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('received_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Deliberately not implemented.

    Alembic generated eighteen drop_table() calls here. Running them on a
    farm server would not "downgrade" anything - it would delete every
    harvest record, worker and payment in the database. There is nothing
    below the baseline to go back to: going back before Boord had a schema
    means restoring a backup, not running a migration.

    Later migrations should carry a real downgrade() where one is possible.
    """
    raise NotImplementedError(
        "There is no downgrade past the baseline schema - restore a backup instead "
        "(data/backups/, and the pre_migration_*.db that migrate.py leaves next to them)."
    )
